### ISSUE TITLE
Code for Membership Inference Attack

### ISSUE THREAD

**Issue by tdemin16** [hnanhtuan/projected_gradient_unlearning#1]
Dear authors,
Could you share your code for the membership inference attack?

Best,
Thomas

**Comment by hnanhtuan** [comment]
Hi Thomas,

Thanks for your interest in our code! I'm happy to share it.

I've pushed the code for MIA  ([MIA.ipynb](https://github.com/hnanhtuan/projected_gradient_unlearning/blob/main/MIA.ipynb) notebook) on our repository.

While I've cleaned up the code for readability, I am sorry that I haven't had a chance to fully debug it yet. However, the notebook should give you a good understanding of the overall process flow. You might need to refer to Figure 13 in the supplementary part of [our paper](https://arxiv.org/pdf/2312.04095.pdf).

Please let me know if you have any questions or encounter any issues. I'm happy to help!

Best regards,

Tuan Hoang

**Comment by tdemin16** [comment]
Thank you very much! Amazing work!

Thomas
